In [ ]:
"""Master Data in NYC taxi data set would be: 
    Zones (location_id,Borough, Zone, Service_Zone)
    Vendors(vendor_id, Name, created_at)
    
    Reference Data:
    
    PaymentType(payment_id, Payment_type)
    RateCode(rate_id, rate_code_type)
    """

In [ ]:
import pandas as pd

In [ ]:
# Importing Data
zone_data = pd.read_csv('./data/taxi_zone_lookup.csv')
zone_data

     LocationID        Borough                     Zone service_zone
0             1            EWR           Newark Airport          EWR
1             2         Queens              Jamaica Bay    Boro Zone
2             3          Bronx  Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan            Alphabet City  Yellow Zone
4             5  Staten Island            Arden Heights    Boro Zone
..          ...            ...                      ...          ...
260         261      Manhattan       World Trade Center  Yellow Zone
261         262      Manhattan           Yorkville East  Yellow Zone
262         263      Manhattan           Yorkville West  Yellow Zone
263         264        Unknown                      NaN          NaN
264         265            NaN           Outside of NYC          NaN

[265 rows x 4 columns]

In [117]:
# Replacing NaN values with Unknown

string_cols = zone_data.select_dtypes(include=["object"]).columns

zone_data[string_cols] = zone_data[string_cols].fillna("Unknown")

In [118]:
# stripping away white spaces for consistency 
def strip_white_space(row):
    for items in row:
        items.strip()
    return row

zone_data[string_cols].apply(strip_white_space, axis='columns')

zone_data

     LocationID        Borough                     Zone service_zone
0             1            EWR           Newark Airport          EWR
1             2         Queens              Jamaica Bay    Boro Zone
2             3          Bronx  Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan            Alphabet City  Yellow Zone
4             5  Staten Island            Arden Heights    Boro Zone
..          ...            ...                      ...          ...
260         261      Manhattan       World Trade Center  Yellow Zone
261         262      Manhattan           Yorkville East  Yellow Zone
262         263      Manhattan           Yorkville West  Yellow Zone
263         264        Unknown                  Unknown      Unknown
264         265        Unknown           Outside of NYC      Unknown

[265 rows x 4 columns]

In [ ]:
# Detecting duplicates

from collections import defaultdict

def detect_duplicates_using_dict(data):

    unique_location = defaultdict(int)
    duplicate_location_id= defaultdict(list)
    
    for _, row in data.iterrows():
        if (row.Borough,row.Zone,row.service_zone) in unique_location:
            duplicate_location_id[unique_location[(row.Borough,row.Zone,row.service_zone)]].append(row.LocationID)
        else:
            unique_location[(row.Borough,row.Zone,row.service_zone)] = row.LocationID
             
    return duplicate_location_id
            
    
detect_duplicates_using_dict(zone_data)


# duplicates using other cols except LocationId 

# data_with_req_attributes = data[['Borough','Zone','service_zone']]

# def find_duplicates(data):
#     duplicates = data[data.duplicated(keep=False)]
#     return duplicates
    
# find_duplicates(data_with_req_attributes)

defaultdict(list, {56: [57], 103: [104, 105]})

In [120]:
zone_data.Borough.unique()

array(['EWR', 'Queens', 'Bronx', 'Manhattan', 'Staten Island', 'Brooklyn',
       'Unknown'], dtype=object)

In [121]:
zone_data.Zone.unique()

array(['Newark Airport', 'Jamaica Bay', 'Allerton/Pelham Gardens',
       'Alphabet City', 'Arden Heights', 'Arrochar/Fort Wadsworth',
       'Astoria', 'Astoria Park', 'Auburndale', 'Baisley Park',
       'Bath Beach', 'Battery Park', 'Battery Park City', 'Bay Ridge',
       'Bay Terrace/Fort Totten', 'Bayside', 'Bedford', 'Bedford Park',
       'Bellerose', 'Belmont', 'Bensonhurst East', 'Bensonhurst West',
       'Bloomfield/Emerson Hill', 'Bloomingdale', 'Boerum Hill',
       'Borough Park', 'Breezy Point/Fort Tilden/Riis Beach',
       'Briarwood/Jamaica Hills', 'Brighton Beach', 'Broad Channel',
       'Bronx Park', 'Bronxdale', 'Brooklyn Heights',
       'Brooklyn Navy Yard', 'Brownsville', 'Bushwick North',
       'Bushwick South', 'Cambria Heights', 'Canarsie', 'Carroll Gardens',
       'Central Harlem', 'Central Harlem North', 'Central Park',
       'Charleston/Tottenville', 'Chinatown', 'City Island',
       'Claremont/Bathgate', 'Clinton East', 'Clinton Hill',
       'Clinton West', 'Co-Op City', 'Cobble Hill', 'College Point',
       'Columbia Street', 'Coney Island', 'Corona', 'Country Club',
       'Crotona Park', 'Crotona Park East', 'Crown Heights North',
       'Crown Heights South', 'Cypress Hills', 'Douglaston',
       'Downtown Brooklyn/MetroTech', 'DUMBO/Vinegar Hill',
       'Dyker Heights', 'East Chelsea',
       'East Concourse/Concourse Village', 'East Elmhurst',
       'East Flatbush/Farragut', 'East Flatbush/Remsen Village',
       'East Flushing', 'East Harlem North', 'East Harlem South',
       'East New York', 'East New York/Pennsylvania Avenue',
       'East Tremont', 'East Village', 'East Williamsburg', 'Eastchester',
       'Elmhurst', 'Elmhurst/Maspeth',
       "Eltingville/Annadale/Prince's Bay", 'Erasmus', 'Far Rockaway',
       'Financial District North', 'Financial District South',
       'Flatbush/Ditmas Park', 'Flatiron', 'Flatlands', 'Flushing',
       'Flushing Meadows-Corona Park', 'Fordham South', 'Forest Hills',
       'Forest Park/Highland Park', 'Fort Greene', 'Fresh Meadows',
       'Freshkills Park', 'Garment District', 'Glen Oaks', 'Glendale',
       "Governor's Island/Ellis Island/Liberty Island", 'Gowanus',
       'Gramercy', 'Gravesend', 'Great Kills', 'Great Kills Park',
       'Green-Wood Cemetery', 'Greenpoint', 'Greenwich Village North',
       'Greenwich Village South', 'Grymes Hill/Clifton',
       'Hamilton Heights', 'Hammels/Arverne',
       'Heartland Village/Todt Hill', 'Highbridge', 'Highbridge Park',
       'Hillcrest/Pomonok', 'Hollis', 'Homecrest', 'Howard Beach',
       'Hudson Sq', 'Hunts Point', 'Inwood', 'Inwood Hill Park',
       'Jackson Heights', 'Jamaica', 'Jamaica Estates', 'JFK Airport',
       'Kensington', 'Kew Gardens', 'Kew Gardens Hills',
       'Kingsbridge Heights', 'Kips Bay', 'LaGuardia Airport',
       'Laurelton', 'Lenox Hill East', 'Lenox Hill West',
       'Lincoln Square East', 'Lincoln Square West',
       'Little Italy/NoLiTa', 'Long Island City/Hunters Point',
       'Long Island City/Queens Plaza', 'Longwood', 'Lower East Side',
       'Madison', 'Manhattan Beach', 'Manhattan Valley', 'Manhattanville',
       'Marble Hill', 'Marine Park/Floyd Bennett Field',
       'Marine Park/Mill Basin', 'Mariners Harbor', 'Maspeth',
       'Meatpacking/West Village West', 'Melrose South', 'Middle Village',
       'Midtown Center', 'Midtown East', 'Midtown North', 'Midtown South',
       'Midwood', 'Morningside Heights', 'Morrisania/Melrose',
       'Mott Haven/Port Morris', 'Mount Hope', 'Murray Hill',
       'Murray Hill-Queens', 'New Dorp/Midland Beach', 'North Corona',
       'Norwood', 'Oakland Gardens', 'Oakwood', 'Ocean Hill',
       'Ocean Parkway South', 'Old Astoria', 'Ozone Park', 'Park Slope',
       'Parkchester', 'Pelham Bay', 'Pelham Bay Park', 'Pelham Parkway',
       'Penn Station/Madison Sq West', 'Port Richmond',
       'Prospect-Lefferts Gardens', 'Prospect Heights', 'Prospect Park',
       'Queens Village', 'Queensboro Hill', 'Queensbridge/Ravenswood',
       'Randalls Island', 'Red Hook', 'Rego Park', 'Richmond Hill',
       'Ridgewood', 'Rikers Island',
       'Riverdale/North Riverdale/Fieldston', 'Rockaway Park',
       'Roosevelt Island', 'Rosedale', 'Rossville/Woodrow',
       'Saint Albans', 'Saint George/New Brighton',
       'Saint Michaels Cemetery/Woodside', 'Schuylerville/Edgewater Park',
       'Seaport', 'Sheepshead Bay', 'SoHo', 'Soundview/Bruckner',
       'Soundview/Castle Hill', 'South Beach/Dongan Hills',
       'South Jamaica', 'South Ozone Park', 'South Williamsburg',
       'Springfield Gardens North', 'Springfield Gardens South',
       'Spuyten Duyvil/Kingsbridge', 'Stapleton', 'Starrett City',
       'Steinway', 'Stuy Town/Peter Cooper Village', 'Stuyvesant Heights',
       'Sunnyside', 'Sunset Park East', 'Sunset Park West',
       'Sutton Place/Turtle Bay North', 'Times Sq/Theatre District',
       'TriBeCa/Civic Center', 'Two Bridges/Seward Park',
       'UN/Turtle Bay South', 'Union Sq',
       'University Heights/Morris Heights', 'Upper East Side North',
       'Upper East Side South', 'Upper West Side North',
       'Upper West Side South', 'Van Cortlandt Park',
       'Van Cortlandt Village', 'Van Nest/Morris Park',
       'Washington Heights North', 'Washington Heights South',
       'West Brighton', 'West Chelsea/Hudson Yards', 'West Concourse',
       'West Farms/Bronx River', 'West Village',
       'Westchester Village/Unionport', 'Westerleigh', 'Whitestone',
       'Willets Point', 'Williamsbridge/Olinville',
       'Williamsburg (North Side)', 'Williamsburg (South Side)',
       'Windsor Terrace', 'Woodhaven', 'Woodlawn/Wakefield', 'Woodside',
       'World Trade Center', 'Yorkville East', 'Yorkville West',
       'Unknown', 'Outside of NYC'], dtype=object)

In [122]:
zone_data.service_zone.unique()

array(['EWR', 'Boro Zone', 'Yellow Zone', 'Airports', 'Unknown'],
      dtype=object)

In [123]:
trip_data = pd.read_parquet('./data/yellow_tripdata_2025-08.parquet')
trip_data

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2025-08-01 00:52:23,2025-08-01 01:12:20,1.0,8.44,1.0,N,138,141,1,33.80,6.0,0.5,5.00,6.94,1.0,57.49,2.5,1.75,0.00
1,2,2025-08-01 00:03:01,2025-08-01 00:15:33,2.0,4.98,1.0,N,138,193,1,21.20,6.0,0.5,0.00,0.00,1.0,30.45,0.0,1.75,0.00
2,7,2025-08-01 00:24:38,2025-08-01 00:24:38,2.0,1.89,1.0,N,249,45,1,14.20,0.0,0.5,3.99,0.00,1.0,23.94,2.5,0.00,0.75
3,7,2025-08-01 00:48:19,2025-08-01 00:48:19,1.0,2.35,1.0,N,79,229,1,11.40,0.0,0.5,3.43,0.00,1.0,20.58,2.5,0.00,0.75
4,2,2025-08-01 00:25:34,2025-08-01 00:33:18,1.0,2.14,1.0,N,43,48,1,11.40,1.0,0.5,2.57,0.00,1.0,19.72,2.5,0.00,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3574086,2,2025-08-31 23:40:30,2025-08-31 23:58:48,NaN,3.12,NaN,None,65,228,0,21.53,0.0,0.5,0.00,0.00,1.0,23.03,NaN,NaN,0.00
3574087,2,2025-08-31 23:10:26,2025-08-31 23:29:01,NaN,5.92,NaN,None,236,148,0,21.78,0.0,0.5,0.00,0.00,1.0,26.53,NaN,NaN,0.75
3574088,2,2025-08-31 23:04:21,2025-08-31 23:25:21,NaN,4.10,NaN,None,148,48,0,-4.75,0.0,0.5,0.00,0.00,1.0,5.83,NaN,NaN,0.75
3574089,2,2025-08-31 23:44:26,2025-08-31 23:44:42,NaN,0.02,NaN,None,107,107,0,12.67,0.0,0.5,0.00,0.00,1.0,17.42,NaN,NaN,0.75
3574090,2,2025-08-31 23:11:01,2025-08-31 23:31:07,NaN,5.07,NaN,None,65,68,0,-4.75,0.0,0.5,0.00,0.00,1.0,10.00,NaN,NaN,0.75

In [124]:
trip_data[trip_data['PULocationID'].isin(['103', '104', '105','56','57'])]
trip_data[trip_data['DOLocationID'].isin(['103', '104', '105','56','57'])]

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge, Airport_fee, cbd_congestion_fee]
Index: []

In [128]:
zone_data

     LocationID        Borough                     Zone service_zone
0             1            EWR           Newark Airport          EWR
1             2         Queens              Jamaica Bay    Boro Zone
2             3          Bronx  Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan            Alphabet City  Yellow Zone
4             5  Staten Island            Arden Heights    Boro Zone
..          ...            ...                      ...          ...
260         261      Manhattan       World Trade Center  Yellow Zone
261         262      Manhattan           Yorkville East  Yellow Zone
262         263      Manhattan           Yorkville West  Yellow Zone
263         264        Unknown                  Unknown      Unknown
264         265        Unknown           Outside of NYC      Unknown

[265 rows x 4 columns]

In [ ]:
# There is no data mentioning the duplicated lOcation id yet, so we can safely delete the duplicate rows

def handle_duplicates(temp_data):
    indices_to_drop = temp_data[temp_data["LocationID"].isin((103,104,56))].index
    zone_data.drop(indices_to_drop, inplace=True)
    
handle_duplicates(zone_data)

Int64Index([], dtype='int64')

,LocationID,Borough,Zone,service_zone
101,102,Queens,Glendale,Boro Zone
104,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
105,106,Brooklyn,Gowanus,Boro Zone
106,107,Manhattan,Gramercy,Yellow Zone
107,108,Brooklyn,Gravesend,Boro Zone
108,109,Staten Island,Great Kills,Boro Zone
109,110,Staten Island,Great Kills Park,Boro Zone